POST http://localhost:3001/api/poruke
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9rdmlyaTkiLCJpZCI6IjYzOThhNTI3MzMwZWU1YzNhYTNlYWVhNiIsImlhdCI6MTY3MDk0OTMyMH0.SyhnFbX4jC8V_hc_pThagvetEFa0t_vfTCQK7Kf9abE

{
  "sadrzaj": "Poruka sa tokenom",
  "vazno": true 
}